FROM python:3.11-slim                                   'system image on which the application will be built'
WORKDIR /app                                            'Folder inside the container where all subsequent commands will be executed'

COPY requirements.txt .                                 'Copy the requirements file in the container'
RUN pip install --no-cache-dir -r requirements.txt      'Install the dependencies required to run the Python application'
COPY app.py .                                           'Copy the source code'
COPY wsgi.py .                                          'Copy the source code'

EXPOSE 5000                                             'Specify the port the app listens to inside the container'
CMD ["gunicorn", "wsgi:app", "--bind", "0.0.0.0:5000"]  'Command that is executed when the container starts, to launch the application'